---
title: "Homework3"
author: "Kitty Harris"
output:
  pdf_document: default
  html_notebook: default
---

### Problems 1-5:

**Voter turnout has been a popular talking point in recent elections. To get a sense of voter turnout in Colorado, a national polling company contacted randomly selected registered Colorado voters until they reached 200 persons who said that they had voted. 303 persons said they had not voted, for a total sample size of 503. The response $y$ is the number of failures before getting the 200th registered voter who had voted. Thus, $y$ can be modeled as a negative binomial distribution with $n$ successes and probability of success (a registered voter stating they voted), i.e., $y|n ~ $Neg-Binom$(n,\theta)$, and 

$$
p(y|n,\theta) = \frac{\Gamma(y+n)}{\Gamma(n)y!}\theta^n(1-\theta)^y.
$$

Based on what you've heard, you believe that the true proportion of registered voters that actually vote is less than 50%, but you're not super confident about this. Thus, you chose a Beta(1.1, 1.5) prior distribution for $\theta$.

### Problem 1:

**Create a graphic of the plotting the likelihood function and the prior density versus $\theta$. Recall that the likelihood function is the data density evaluated at the observed data values as a function of $\theta$. Make sure to scale the likelihood function so that its mode is similar to the mode of the prior. Make sure to provide a legend distinguishing the two functions.**

```{R}
theta = seq(0, 1, length.out=100)
likelihood = function(th){ #unnormalized
  return(th^200*(1-th)^303*.9e147)
}
prior = function(th){
  return(dbeta(th,shape1=1.1,shape2=1.5))
}
#print(gamma(503)/(gamma(200)*gamma(304)))
#print(likelihood(theta))
plot(theta,likelihood(theta),ylab='Unnormalized Probability')
points(theta,prior(theta),col='blue')
legend(.8,1.3,c("likelihood","prior"),c("black","blue"))
```

