---
title: "Summary of Presentations"
author: "Kitty Harris"
date: "2023-05-05"
output: pdf_document
fontsize: 12pt
---

# Converting Disused Lots to Housing: Equitable locations for new housing
## Michael Schmidt

This project aims to find suitable unused lots to convert into housing. After the housing bubble burst in the mid-to-late 2000s, housing supply has gone back down while housing prices have increased, especially from 2020 into 2021. While converting empty lots may seem like an obvious solution to Denver's affordable housing shortage, and has been recommended almost unanimously by upcoming mayoral candidates, not all empty lots make suitable housing. However, we cannot afford to ignore this option for addressing housing; the deficit for housing is "between 14,604 and 62,606 units," and is over 100,000 for those affordable to households with an income of under \$20,000 annually. Furthermore, at current construction rates, this shortage "will take over 100 years to eliminate." It should be noted that it is still not agreed upon what public land, e.g. parks, can be used or sold for housing development. The study only considers locations within a twenty-minute walking distance of a school, a light rail station, and a supermarket, as it considers each of these crucial for equitable housing. From here, the project looks at maximizing employment access and minimizing the total cost of living at the location. Suitable locations were found for roughly a thousand homes with the walking distance requirements while also being within a twenty-minute walking distance of a total of 14000 local jobs. The estimated cost of this land is \$13 million. Future work includes examining not only completely vacant lots but also disused lots, developing a more advanced model for transportation access, and minimizing the total cost of the land selected for the housing project. A link to the code used for the generation of plots associated with this analysis is provided.

\newpage

# Smoking Habits
## Riley Lamont

This project looks at smoking habits of the population of the United States. In 2020, about 12.5% of the adult U.S. population smoked cigarettes, and smoking accounts for at least 480,000 deaths each year. Data was collected from the American Time Use Survey, which interviews randomly selected households who participated in the Current Population Survey about their activities on the day before the interview. This analysis focuses only on those who considered their smoking to be a primary activity. Individuals tended to smoke more sporadically when not working, while we see large spikes in smoking for those at work -- these likely correspond to work breaks. The response variable used was minutes spent smoking each day and was analyzed using a negative binomial regression model to account for overdispersion. Models were selected by combining different variables and using WAIC and LOOIC to compare how well they fit to the data. Although the analysis started with covariates for industry, age, marital status, family income, veteran status, employment status, birth country, sex, household size, metro, and education level, only age and employment status (binary employed or unemployed) were found to be significant variables. The baseline smoking time for smokers is 24 minutes a day, with employment decreasing time spent smoking by 23.4% and age increasing time spent smoking by 0.6% for each year. The model, however, does not account for the variability of the data; a nominal regression model with different categroies for different types or amounts of smoking may fit better. Policies proposed include targeting anti-smoking advertisements mid-day when unemployed individuals may be home and influencing younger generations not to smoke to reduce the chance they will smoke when they are older.

\newpage

# A Bayesian Autoregressive Model of Fuel Moisture in Colorado
## Jonathon Hirschi

FMC, or dry fuel moisture content, measures the amount of water in dead wood as this is a key player in the spread of wildfires. It is measured by the NOAA through Remote Access Weather Stations (RAWS) alongside other environmental factors, and this data is available through the Mesonet API. This project looks at data from the RAWS and builds a model relating FMC to other environmental variables to predict the FMC at unobserved locations. This prediction would allow us to identify areas of high uncertainty in order to identify the most important locations for new stations. The data consists of 44 RAWS in Colorado with data available for relevant variables over the time period of June 1-30, 2022. There is some apparent correlation between the time and the moisture, as there is a peak in the FCM around noon each day, and there also appears to be a jump in FCM each time it rains. The analysis uses a 20-day training period for a 10-day forecast period; the prediction method used is standard in meteorology. A 70/30 training split for the predictive model is also used on the RAWS locations. The two key predictors for FMC were temperature and relative humidity. Equilibrium Moisture Content describes the theoretical water content of a piece of wood that has been exposed to a particular temperature and relative humidity combination for a long time. An autoregressive model was used to account for the time it takes wood to accumulate or lose moisture -- other contributing variables in the final model were rain, EMC, and wind; although time and elevation were also considered, they were found not to significantly affect the FMC. A map is provided of areas with significant forecast error, ranging from 0.4 to 1.6, and a recommendation is made for two new monitoring stations in Southwest Colorado where the FMC forecast error was largest to improve monitoring in these regions.

\newpage

# Using Regression Models to Understand Public Transit
## Cullen Sainey

The goals of this project are to create models explaining public transportation use and extrapolate from those models how much use public transportation would see in new cities. The data includes the total number of passenger miles traveled, service area in square miles, the population of the area, expenditure associated with the transit system, the service of urbanized areas, and "unlinked passenger trips," or the number of trips that occur that are not considered to be associated with each other (for example, a transfer from one train line to another would be counted as one trip). In an initial exploration, the most relevant variables for passenger miles were population density and the number of unlinked trips. Analysis began with a model using five regressors, but was trimmed down to three by the end. The best fit model used population density, unlinked trips, and expenses per square mile as the most relevant variables in determining the total passenger miles. However, there were issues with the structure of the model that went unresolved; it is possible that this could be resolved by refining the model through transformation or by using additional variables that were not available for this study -- for example, cleanliness and size of the vehicles. Expenses per square mile decreased the number of passenger miles, while the population density and number of trips increased the passenger miles. The intercept for the regression model is unclear, as the 95\% confidence interval ranges from $-$600 thousand to 840 thousand. From this, the author concludes that denser cities are the best candidates for expansion of transportation systems, although specific cities are not named. They also reiterate that there are other variables that were not consider that may impact usage, and therefore further study is needed.

\newpage

# Financial and Academic Factors' Impact on U.S. Undergraduate Program Completion Rates
## Eric Flores, Mikias Mengistu, Brock Sowa, and Aragorn Wang

The data used for this project comes from the U.S. Department of Education's College Scorecard, which contains data from 6681 higher education institutions about things such as test scores and retention rates. Most of the numeric variables are rounded to integer values. The goal of the project is to predict how different factors affect college completion rates so that completion rates can be improved. Completion rates are defined as the percentage of students who complete their program within double the time the institution expects them to finish. Factors considered include SAT scores, percent of faculty that is considered full-time, average faculty salary, per-student expenditure, average family income for students, and the average cost of attendance. Values used are two-year averages for each university. In an initial exploration of the data, the completion rate for public and private but non-profit institutions had similar mean completion rates above 50\%, while private for-profit institutions have mean completion rates much lower, below 25\%. There is a positive linear relationship between completion rate and all of SAT scores, family income, and average faculty salary, and no apparent relationship between completion rate and either percentage of full-time faculty or student expenditure. There is also a positive relationship between cost of attendance and completion rate, but the slope differs for each institution type; the slope is steepest for public institutions, leading the authors to conclude that it has only a marginal benefit. Variables found in analysis to be significant were SAT scores, average faculty salary, family income, cost of attendance, and institution type. The relationships between the explanatory variables and the completion rate are all similar to those described above. Notably, completion rates at private non-profit institutions are 13\% higher than for public institutions, while they are almost 60\% lower than the public average for private for-profit institutions. Similarly, cost of attendance was least relevant for private non-profit institutions and most relevant for private for-profit institutions. Average of SAT scores and faculty salary were the other most significant variables. The authors recommend reduced-cost or free remedial math and language courses as well as focused mentorship and counseling in order to help students with lower standardized test scores. Institutions can also improve completion rates by offering competitive salaries. It is also recommended that prospective students seek counseling regarding potentially attending private schools, and the authors note that students should not consider cost of attendance or family income as major factors in their prospective completion rates.